name: 'Telegram Message Notify'
description: 'Sending a Telegram message'
author: 'Bo-Yi Wu'

inputs:
  to:
    description: 'telegram user'
    required: true
  token:
    description: 'telegram token'
    required: true
  message:
    description: 'telegram message'
  message_file:
    description: 'overwrite the default message template with the contents of the specified file'
  socks5:
    description: 'support socks5 proxy URL'
  photo:
    description: 'send the photo message.'
  document:
    description: 'send the document message.'
  sticker:
    description: 'send the sticker message.'
  audio:
    description: 'send the audio message.'
  voice:
    description: 'send the voice message.'
  location:
    description: 'send the location message.'
  venue:
    description: 'send the venue message.'
  video:
    description: 'send the video message.'
  debug:
    description: 'enable debug mode.'
  format:
    description: 'message format: markdown or html'
  disable_web_page_preview:
    description: 'disables link previews for links in this message'
  disable_notification:
    description: 'disables notifications for this message, supports sending a message without notification,'

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download drone-telegram binary
      shell: bash
      run: |
        curl -L -o /bin/drone-telegram https://github.com/appleboy/drone-telegram/releases/download/v1.3.10/drone-telegram-v1.3.10-darwin-amd64
        chmod +x /bin/drone-telegram

    - name: Run Telegram Notify Script
      shell: bash
      run: |
        chmod +x $GITHUB_WORKSPACE/entrypoint.sh
        $GITHUB_WORKSPACE/entrypoint.sh ${{ inputs.message }}

branding:
  icon: 'message-square'
  color: 'blue'